name: Repo --> Staging

on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1 

      - name: Install dependencies to be able to build
        run: bun install 

      - name: Run script
        run: bun build