name: Repo --> Staging

on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest 

    env:
      IMAGE_INLINE_SIZE_LIMIT: '0'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies to be able to build
        run: npm i  
        
      - name: Build
        run: CI=false npm run build  

      - name: Upload 
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }} 
          server-dir: /staging.weightxreps.net/
          local-dir: ./build/