name: Repo --> Staging

on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest 

    env:
      IMAGE_INLINE_SIZE_LIMIT: '0'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install dependencies to be able to build
        run: pnpm install --strict-peer-dependencies=false
        
      - name: Build
        run: CI=false pnpm run build 

      - name: Upload 
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }} 
          server-dir: /staging.weightxreps.net/
          local-dir: ./build/