name: Staging --> Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:  
      - name: Copy from Staging to Production
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            rsync -av --chmod=ugo+rwx --exclude="notif.txt" --exclude=".htaccess" --exclude=".ftp-deploy-sync-state.json" --exclude="wxr-server-2" --exclude=".well-known" --exclude="cgi-bin" /home/${{ secrets.USER }}/staging.weightxreps.net/. /home/${{ secrets.USER }}/public_html/weightxreps.net/ 

#
# 1) Almost had a heart attack... if you dont set the permission to 0755 the server will throw 404 on all files... omg... 
# 2) Don't override the .htaccess because it has old stuff that make other old stuff work...
#